v
d e
d r
s s a
b a { 1 2 3 4 5 } 
b b { 1 3 5 }
b c { 2 3 4 5 6 }
b eSet { }
p test
h
o a
o b
o c

= r b
o r
= e e
o r
= r r
o r

+ r a b
o r
+ r b c
o r
+ r a a 
o r
+ r s a
o r
+ r a s
o r
+ r e e
o r

- r a b
o r
- r b c
o r
- r a a
o r
- r a e
o r
- r e a
o r
- r e e
o r
- r a s
o r
- r s a
o r

* r a b
o r
* r b c
o r
* r a a 
o r
* r b a 
o r
* r c b
o r
* r a s
o r
* r s a 
o r
* r e a
o r
* r a e
o r
* r e e
o r
p quit
q


