#!/bin/csh

set usage = "Usage: $0"
set version = "Version 0.3"

# In batch mode run a bunch of tests and strip
# off a bunch of the sys161 and OS/161 output
# that isn't relevant and makes it harder to find
# the desired output.


# This is a list of the test programs to run.
set list = (vm-basic vm-crash vm-replace vm-big-no-fork vm-consecutive)

set STRIP = ./strip-text

echo "RUNNING $0 : $version"

if ($#argv != 0) then
    echo "$usage"
    exit 1
endif

foreach i ($list) 
  echo "---------------------------------------------------------------"
  echo "RUNNING test-$i TESTS"
  ./test-$i |& $STRIP
  echo ""
end

exit 0

