#!/bin/csh

# This requires at least argc to be set to a
# value not equal to 2 so we don't use it.
# ./test-vm-ctest
# echo "-----------"
./test-vm-sort
echo "-----------"
./test-vm-matmult
echo "-----------"
./test-vm-huge
echo "-----------"
sys161 kernel "p newtests/vm-data3;q"
echo "-----------"
sys161 kernel "p newtests/vm-crash3;q"
echo "-----------------------------------------"
