#!/bin/csh

# Try writing to write protected page
sys161 kernel "p newtests/vm-crash1;q"
echo "-----------------------------------------"
sys161 kernel "p newtests/vm-crash2;q"
echo "-----------------------------------------"
