#!/bin/csh

echo "abcdefghijklmnopqrstuvwzyz" > tailfile
sys161 kernel "p testbin/tail tailfile 0;q"
sys161 kernel "p testbin/tail tailfile 1;q"
sys161 kernel "p testbin/tail tailfile 2;q"
sys161 kernel "p testbin/tail tailfile 24;q"
sys161 kernel "p testbin/tail tailfile 25;q"
sys161 kernel "p testbin/tail tailfile 26;q"

